---
- hosts: all
  become: true
  tasks:
    - name: yum install epl
      yum:
        name:
          - epel-release

    - name: yum install 
      yum:
        name:
          - iperf3
          - openvpn


  # handlers:
  #   - name: reload frr
  #     systemd:
  #       name: frr
  #       # state: reloaded
  #       state: restarted
  #       enabled: true