all:
  hosts:
    vagrant_1:
      ansible_host: "{{ ansible_ssh_host }}"
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2222
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/nginx/virtualbox/private_key
      # ansible_python_interpreter: /usr/bin/python3

pam:
  hosts:
    vagrant_1:
  vars:
    users: 
      - name: "admin"
        pass: "$6$rNk.RIawXvIrRsqu$BnyDhW4YFAIzaEeC3dPZw3/fflyaSPizdjYnCKzGb2xScY0F29Q2MNdEvGAtfZvtY1tCXYSM596f.e6jgYANM0"
      - name: "user1"
        pass: "$6$rNk.RIawXvIrRsqu$BnyDhW4YFAIzaEeC3dPZw3/fflyaSPizdjYnCKzGb2xScY0F29Q2MNdEvGAtfZvtY1tCXYSM596f.e6jgYANM0"
      - name: "user2"
        pass: "$6$rNk.RIawXvIrRsqu$BnyDhW4YFAIzaEeC3dPZw3/fflyaSPizdjYnCKzGb2xScY0F29Q2MNdEvGAtfZvtY1tCXYSM596f.e6jgYANM0"


